### ISSUE TITLE
[Опционально] Легко засофтлочиться 

### ISSUE THREAD

**Issue by Tetrergeru** [Denis0014/Cubeacon#31]
На многих уровнях легко притащить блок в стенку и запороть себе прохождение. Возможно это задумывалось геймдизайнером как часть головоломки, но на практике в большинстве случаев ощущается просто странно. Можно попробовать обойти это расставив в тех местах, где это не важно для головоломки какой-то бордюр, через который игрок ходить может, а зеркала двигаться — нет

**Comment by Denis0014** [comment]
Мы планируем добавить механику отката действий, как в "Baba is you", aka Ctrl + Z

**Comment by Denis0014** [comment]
#37 
Работа началась!

**Comment by Denis0014** [comment]
Механика, решающая проблему была добавлена. Вопрос закрыт!
